#!/bin/bash
set -e

DOMAIN="${1:-}"
COMPOSE="docker compose -f docker-compose.prod.yml"

# ─── helpers ────────────────────────────────────────────────────────────────

usage() {
  echo "Usage:"
  echo "  ./deploy.sh setup <yourdomain.com>   # first time: get SSL cert + start stack"
  echo "  ./deploy.sh update                   # pull code, rebuild, migrate, restart"
  exit 1
}

require_env() {
  if [ ! -f backend/.env ]; then
    echo "ERROR: backend/.env not found. Copy backend/.env.example and fill in values."
    exit 1
  fi
}

# docker-compose.prod.yml interpolates ${DB_DATABASE}/${VITE_APP_NAME}/etc.
# from a root-level .env — a file Docker Compose reads but backend/.env
# never fills in. Regenerating it here from backend/.env (the single file
# anyone actually edits) means there's no second .env to remember to keep
# in sync by hand.
generate_root_env() {
  local db_database db_username db_password reverb_app_key app_name

  db_database=$(grep -m1 '^DB_DATABASE=' backend/.env | cut -d= -f2-)
  db_username=$(grep -m1 '^DB_USERNAME=' backend/.env | cut -d= -f2-)
  db_password=$(grep -m1 '^DB_PASSWORD=' backend/.env | cut -d= -f2-)
  reverb_app_key=$(grep -m1 '^REVERB_APP_KEY=' backend/.env | cut -d= -f2-)
  app_name=$(grep -m1 '^APP_NAME=' backend/.env | cut -d= -f2- | tr -d '"')

  cat > .env <<-EOF
	# Generated by deploy.sh from backend/.env — do not edit by hand, re-run deploy.sh instead.
	DB_DATABASE=${db_database}
	DB_USERNAME=${db_username}
	DB_PASSWORD=${db_password}
	VITE_APP_NAME=${app_name:-Shopping List}
	VITE_REVERB_APP_KEY=${reverb_app_key}
	EOF

  echo "→ Regenerated root .env from backend/.env."
}

# ─── setup (first deployment) ────────────────────────────────────────────────

setup() {
  DOMAIN="${1:-}"
  [ -z "$DOMAIN" ] && { echo "ERROR: domain required. Usage: ./deploy.sh setup yourdomain.com"; exit 1; }

  require_env
  generate_root_env

  # Render the DOMAIN placeholder into a generated file, never the tracked
  # template — running setup again (or update, via git pull) must never
  # fight over a file git also manages.
  sed "s/DOMAIN/$DOMAIN/g" docker/nginx/default.prod.conf.template > docker/nginx/default.prod.conf

  echo "→ Starting nginx on port 80 for ACME challenge..."
  $COMPOSE up -d nginx certbot postgres

  echo "→ Obtaining SSL certificate for $DOMAIN..."
  docker run --rm \
    -v shopping_certbot_certs:/etc/letsencrypt \
    -v shopping_certbot_www:/var/www/certbot \
    certbot/certbot certonly \
      --webroot \
      --webroot-path /var/www/certbot \
      --email "$(grep APP_URL backend/.env | grep -oP '(?<=@)[^>]+' || echo admin@$DOMAIN)" \
      --agree-tos \
      --no-eff-email \
      -d "$DOMAIN"

  echo "→ Building and starting full stack..."
  $COMPOSE up -d --build

  echo "→ Running migrations..."
  $COMPOSE exec php php artisan migrate --force

  echo "✓ Done. App is running at https://$DOMAIN"
}

# ─── update (subsequent deployments) ─────────────────────────────────────────

update() {
  require_env

  echo "→ Pulling latest code..."
  git pull

  generate_root_env

  echo "→ Rebuilding images..."
  $COMPOSE build --no-cache php nginx

  echo "→ Restarting services..."
  $COMPOSE up -d

  echo "→ Running migrations..."
  $COMPOSE exec php php artisan migrate --force

  echo "→ Clearing old caches..."
  $COMPOSE exec php php artisan cache:clear

  echo "✓ Update complete."
}

# ─── entry point ─────────────────────────────────────────────────────────────

case "${1:-}" in
  setup)  setup "$2" ;;
  update) update ;;
  *)      usage ;;
esac
